parameters:
#    sdz_user.example.class: Sdz\UserBundle\Example

services:
    sdz_user.logouthandler:
        class: Sdz\UserBundle\Handler\LogoutHandler
#        arguments: [@service_id, "plain_value", %parameter%]
