<?php

namespace Sdz\ATIBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeRepository extends EntityRepository
{
	public function getEntrees($nombreParPage,$page)
	{
		if ($page < 1)
		{
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		
		$query = $this->createQueryBuilder('e')
					  ->leftJoin('e.magasin','m')
					  ->addSelect('m')
					  ->leftJoin('e.produit','p')
					  ->addSelect('p')
					  ->leftJoin('e.user','u')
					  ->addSelect('u')
					  ->orderBy('p.date','DESC')
					  ->getQuery();
					  
		$query->setFirstResult(($page-1)*$nombreParPage)
			  ->setMaxResults($nombreParPage);
		
		
					  
		return new Paginator($query);
	}
}
