<?php

namespace Sdz\ATIBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MagasinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagasinRepository extends EntityRepository
{
	public function getMagasins($nombreParPage,$page)
	{
		if ($page < 1) 
		{
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		
		$query = $this->createQueryBuilder('m')
					  ->orderBy('m.nom','ASC')
					  ->getQuery();
					  
		$query->setFirstResult(($page-1)*$nombreParPage)
			  ->setMaxResults($nombreParPage);
		
		
					  
		return new Paginator($query);
	}
}
