<?php

namespace Sdz\ATIBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
	
	public function getProduits($nombreParPage,$page)
	{
		if ($page < 1)
		{
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		
		$query = $this->createQueryBuilder('p')
					  ->leftJoin('p.picture','pi')
					  ->addSelect('pi')
					  ->orderBy('p.date','DESC')
					  ->getQuery();
					  
		$query->setFirstResult(($page-1)*$nombreParPage)
			  ->setMaxResults($nombreParPage);
		
		
					  
		return new Paginator($query);
	}

	public function getProduitlimit($limit)
	{
		$query = $this->createQueryBuilder('p')
					  ->where('p.qted < :limit')
			  		  ->setParameter('limit', $limit)
					  ->orderBy('p.nom','DESC')
					  ->getQuery();
				  
		return $query->getResult();

	}
}
