<?php

namespace Sdz\ATIBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Produit_MagasinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitMagasinRepository extends EntityRepository
{
	public function getProduitMagasin(Magasin $magasin,$nombreParPage,$page)
	{
		if ( (int) $page < 1)
		{
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
		}
		
		$query = $this->createQueryBuilder('p');
		$query->leftjoin('p.magasin', 'm')
			  
			  ->where('m.id = :magasin')
			  ->setParameter('magasin', $magasin->getId());



  
		$query->setFirstResult(($page-1)*$nombreParPage)
			  ->setMaxResults($nombreParPage);
				  
		return new Paginator($query);
	}


	public function myfindAll(Magasin $magasin)
	{
		
		$query = $this->createQueryBuilder('p');
		$query->leftjoin('p.magasin', 'm')
		      ->addSelect('m')
		      ->leftjoin('p.produit','pr')
		      ->addSelect('pr')
			  
			  ->where('m.id = :magasin')
			  ->setParameter('magasin', $magasin->getId());

			 $qd = $query->getQuery();


  
		
				  
		return $qd->getResult();
	}
}
