<?php

namespace Sdz\ATIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends EntityRepository
{
	

	public function findStatmois($pid,$annee,$mois)
	{
		$query = $this->createQueryBuilder('s')
					  ->leftjoin('s.produit','p')
				      ->addSelect('p')
				      ->andWhere('p.id = :pid')
				      ->setParameter('pid',$pid)
				      ->andWhere('s.annee = :annee')
		      		  ->setParameter('annee',$annee)
		      		  ->andWhere('s.mois = :mois')
		      		  ->setParameter('mois',$mois);

		      	return $query->getQuery()->getOneOrNullResult();

	}

	public function findStatannee($pid,$annee)
	{
		$query = $this->createQueryBuilder('s')
					  ->leftjoin('s.produit','p')
				      ->addSelect('p')
				      ->andWhere('p.id = :pid')
				      ->setParameter('pid',$pid)
				      ->andWhere('s.annee = :annee')
		      		  ->setParameter('annee',$annee);

		      	return $query->getQuery()->getResult();

	}

	public function findStatcourant($mois,$annee)
	{
		$query = $this->createQueryBuilder('s')
					  ->leftjoin('s.produit','p')
				      ->addSelect('p')
				      ->Where('s.annee = :annee')
		      		  ->setParameter('annee',$annee)
		      		  ->andWhere('s.mois = :mois')
		      		  ->setParameter('mois',$mois);

		return $query->getQuery()->getResult();
	}

	public function findStatbyannee($annee)
	{
		$query = $this->createQueryBuilder('s')
					  ->leftjoin('s.produit','p')
				      ->addSelect('p')
				      ->Where('s.annee = :annee')
		      		  ->setParameter('annee',$annee);

		return $query->getQuery()->getResult();
	}

	public function findStatmoisannee($annee)
	{
		$query = $this->createQueryBuilder('s')
					  ->leftjoin('s.produit','p')
				      ->addSelect('p')
				      ->Where('s.annee = :annee')
		      		  ->setParameter('annee',$annee);

		return $query->getQuery()->getResult();
	}

	public function findStatAllmonth($annee)
	{
		$query = $this->_em->createQuery('SELECT DISTINCT s.mois FROM SdzATIBundle:Statistique s WHERE s.annee = :annee');
		$query->setParameter('annee', $annee);
		return $query->getScalarResult();
	}

	public function findStatAllyear()
	{
		$query = $this->_em->createQuery('SELECT DISTINCT s.annee FROM SdzATIBundle:Statistique s');
		return $query->getScalarResult();
	}

	


}
