<?php

namespace Sdz\ATIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatMagasinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatMagasinRepository extends EntityRepository
{
	
	
	public function findStatMannee($mid,$pid,$annee)
	{
		$query = $this->createQueryBuilder('s')
					  ->leftjoin('s.magasin','m')
					  ->addSelect('m')
					  ->where('m.id = :mid')
					  ->setParameter('mid', $mid)
					  ->leftjoin('s.produit','p')
				      ->addSelect('p')
				      ->andWhere('p.id = :pid')
				      ->setParameter('pid',$pid)
				      ->andWhere('s.annee = :annee')
		      		  ->setParameter('annee',$annee);

		      	return $query->getQuery()->getResult();

	}

	public function findStatMmois($mid,$pid,$annee,$mois)
	{
		$query = $this->createQueryBuilder('s')
					  ->leftjoin('s.magasin','m')
					  ->addSelect('m')
					  ->where('m.id = :mid')
					  ->setParameter('mid', $mid)
					  ->leftjoin('s.produit','p')
				      ->addSelect('p')
				      ->andWhere('p.id = :pid')
				      ->setParameter('pid',$pid)
				      ->andWhere('s.annee = :annee')
		      		  ->setParameter('annee',$annee)
		      		  ->andWhere('s.mois = :mois')
		      		  ->setParameter('mois',$mois);

		      	return $query->getQuery()->getOneOrNullResult();

	}


}
